bindsym $mod+1 workspace "1:work"
bindsym $mod+Shift+1 move container to workspace "1:work"
bindsym $mod+Ctrl+1 workspace "2:wextra"
bindsym $mod+Ctrl+Shift+1 move container to workspace "2:wextra"
for_window [app_id="code-oss"] move window to workspace "1:work" ; workspace "1:work"
for_window [app_id="nvim-qt"] move window to workspace "1:work" ; workspace "1:work"
for_window [app_id="kicad"] move window to workspace "1:work" ; workspace "1:work"
bindsym $mod+2 workspace "3:browser"
bindsym $mod+Shift+2 move container to workspace "3:browser"
bindsym $mod+Ctrl+2 workspace "4:bextra"
bindsym $mod+Ctrl+Shift+2 move container to workspace "4:bextra"
for_window [app_id="Firefox"] move window to workspace "3:browser" ; workspace "3:browser"
bindsym $mod+3 workspace "5:term"
bindsym $mod+Shift+3 move container to workspace "5:term"
bindsym $mod+Ctrl+3 workspace "6:textra"
bindsym $mod+Ctrl+Shift+3 move container to workspace "6:textra"
bindsym $mod+4 workspace "7:misc"
bindsym $mod+Shift+4 move container to workspace "7:misc"
bindsym $mod+Ctrl+4 workspace "8:mextra"
bindsym $mod+Ctrl+Shift+4 move container to workspace "8:mextra"
for_window [app_id="thunar"] move window to workspace "7:misc" ; workspace "7:misc"
bindsym $mod+5 workspace "9:daemon"
bindsym $mod+Shift+5 move container to workspace "9:daemon"
bindsym $mod+Ctrl+5 workspace "10:dextra"
bindsym $mod+Ctrl+Shift+5 move container to workspace "10:dextra"
bindsym $mod+6 workspace "11:media"
bindsym $mod+Shift+6 move container to workspace "11:media"
bindsym $mod+Ctrl+6 workspace "12:mextra"
bindsym $mod+Ctrl+Shift+6 move container to workspace "12:mextra"
for_window [app_id="com.discordapp.Discord"] move window to workspace "11:media" ; workspace "11:media"
for_window [class="Spotify"] move window to workspace "11:media" ; workspace "11:media"
bindsym $mod+7 workspace 7
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+Shift+9 move container to workspace 9
