#!/bin/bash

OUTPUT=/tmp/xbps-updates.txt

while true; do
	updates=$(xbps-install -Mun | wc -l)

	if [ $updates -ne 0 ]; then
	    echo $updates > $OUTPUT
	else
	    echo up-to-date > $OUTPUT
	fi
	sleep 120
done
