#font_family     family="Red Hat Mono" weight=600 features="-liga"
font_family     family="Monaco Nerd Font Mono" features="-liga"
italic_font     family="Go Mono" style=italic
bold_font       auto weight=1000
font_size       9
#modify_font     cell_width 80%

window_margin_width 2

#include onedark.conf


# BEGIN_KITTY_THEME
# Doom One
include current-theme.conf
# END_KITTY_THEME
